### ISSUE TITLE
SEGFAULT using new functions scard_begin_transaction()

### ISSUE THREAD

**Issue by hanez** [pcsc-for-php/pcsc#3]
I added two new functions and don't know why I get a segfault when invoking scard_begin_transaction()...

I am not that deep into PECL extension debugging so I can not figure out what is going wrong.

When running ./docs/examples/simple.php I get a segmentation fault when executing the script on line 647 in pcsc.c:

ZEND_FETCH_RESOURCE(hCard, SCARDHANDLE, &conn_res, -1, PHP_PCSC_CONN_RES_NAME, le_pcsc_conn_res);

GDB gives me this:

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff4b1c611 in zif_scard_begin_transaction (execute_data=0x7ffff52136d0, return_value=0x7ffff5213370)
    at /home/hanez/code/pcsc-for-php/pcsc/pcsc.c:647
647       ZEND_FETCH_RESOURCE(hCard, SCARDHANDLE, &conn_res, -1, PHP_PCSC_CONN_RES_NAME, le_pcsc_conn_res);

I believe I did everything right but it seems I didn't... :(

Can someone explain what is wrong or give me some hints how to debug this?

**Comment by NattyNarwhal** [comment]
FWIW it might be a good idea to rebuild PHP with`--enable-debug`, if you haven't.

**Comment by hanez** [comment]
Ok,
I installed PHP with latest sources from GitHub but nnow I get the following error at compile time which I do not understand because the code looks Ok to me and the two new functions I added are part of the compile error.

One thing I made not the "PHP way" is that I didn't generated the *arginfo.h files from the pcsc.stub.php file but I made all changes by hand because I don't know how to generate these files... could that be the source of the error?

PHP 8.1.0-dev (cli) (built: Feb 23 2021 20:06:32) ( NTS DEBUG )
Copyright (c) The PHP Group
Zend Engine v4.1.0-dev, Copyright (c) Zend Technologies

/bin/sh /home/hanez/code/pcsc-for-php/pcsc/libtool --mode=compile cc -I. -I/home/hanez/code/pcsc-for-php/pcsc -I/home/hanez/code/pcsc-for-php/pcsc/include -I/home/hanez/code/pcsc-for-php/pcsc/main -I/home/hanez/code/pcsc-for-php/pcsc -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/usr/include/PCSC/  -DHAVE_CONFIG_H  -g -O0    -c /home/hanez/code/pcsc-for-php/pcsc/pcsc.c -o pcsc.lo  -MMD -MF pcsc.dep -MT pcsc.lo
 cc -I. -I/home/hanez/code/pcsc-for-php/pcsc -I/home/hanez/code/pcsc-for-php/pcsc/include -I/home/hanez/code/pcsc-for-php/pcsc/main -I/home/hanez/code/pcsc-for-php/pcsc -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/usr/include/PCSC/ -DHAVE_CONFIG_H -g -O0 -c /home/hanez/code/pcsc-for-php/pcsc/pcsc.c -MMD -MF pcsc.dep -MT pcsc.lo  -fPIC -DPIC -o .libs/pcsc.o
In file included from /usr/include/php/main/php.h:35,
                 from /home/hanez/code/pcsc-for-php/pcsc/pcsc.c:21:
/home/hanez/code/pcsc-for-php/pcsc/pcsc_arginfo.h:73:36: error: ‘arginfo_scard_begin_transaction’ undeclared here (not in a function); did you mean ‘zif_scard_begin_transaction’?
   73 |   ZEND_FE(scard_begin_transaction, arginfo_scard_begin_transaction)
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/php/Zend/zend_API.h:77:80: note: in definition of macro ‘ZEND_RAW_FENTRY’
   77 | #define ZEND_RAW_FENTRY(zend_name, name, arg_info, flags)   { zend_name, name, arg_info, (uint32_t) (sizeof(arg_info)/sizeof(struct _zend_internal_arg_info)-1), flags },
      |                                                                                ^~~~~~~~
/home/hanez/code/pcsc-for-php/pcsc/pcsc_arginfo.h:73:3: note: in expansion of macro ‘ZEND_FE’
   73 |   ZEND_FE(scard_begin_transaction, arginfo_scard_begin_transaction)
      |   ^~~~~~~
/home/hanez/code/pcsc-for-php/pcsc/pcsc_arginfo.h:74:34: error: ‘arginfo_scard_end_transaction’ undeclared here (not in a function); did you mean ‘zif_scard_end_transaction’?
   74 |   ZEND_FE(scard_end_transaction, arginfo_scard_end_transaction)
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/php/Zend/zend_API.h:77:80: note: in definition of macro ‘ZEND_RAW_FENTRY’
   77 | #define ZEND_RAW_FENTRY(zend_name, name, arg_info, flags)   { zend_name, name, arg_info, (uint32_t) (sizeof(arg_info)/sizeof(struct _zend_internal_arg_info)-1), flags },
      |                                                                                ^~~~~~~~
/home/hanez/code/pcsc-for-php/pcsc/pcsc_arginfo.h:74:3: note: in expansion of macro ‘ZEND_FE’
   74 |   ZEND_FE(scard_end_transaction, arginfo_scard_end_transaction)
      |   ^~~~~~~
make: *** [Makefile:206: pcsc.lo] Error 1

**Comment by hanez** [comment]
Okay, the SEGFAULT is gone using PHP 7.4.16-dev with --enable-debug.

Still scard_begin_transaction() does not work but I need to investigate this a little bit more.
