### ISSUE TITLE
help to send getuid apdu

### ISSUE THREAD

**Issue by meysamsalehi** [pcsc-for-php/pcsc#6]
Hi 
Thanks for project 

How to send apdu for getUid ? 

Please help me.
#

**Comment by hanez** [comment]
I don't know what you mean. It seems this is application specific or is it some kind of standard?

You just need to send an APDU for the application specific function using the scard_transmit($connection, $apdu) function defined by the PCSC API. This should then return the Uid...

Take a look at https://github.com/pcsc-for-php/pcsc/blob/master/docs/examples/simple.php on how to connect to a card and transmit an APDU to get the return value. If you give me the APDU for getUid I could maybe help you a little bit more but I think this is the wrong place for that.

**Comment by hanez** [comment]
Closing this. Not a "pcsc-for-php" issue...

**Comment by meysamsalehi** [comment]
> 
> 
> I don't know what you mean. It seems this is application specific or is it some kind of standard?
> 
> You just need to send an APDU for the application specific function using the scard_transmit($connection, $apdu) function defined by the PCSC API. This should then return the Uid...
> 
> Take a look at https://github.com/pcsc-for-php/pcsc/blob/master/docs/examples/simple.php on how to connect to a card and transmit an APDU to get the return value. If you give me the APDU for getUid I could maybe help you a little bit more but I think this is the wrong place for that.

hello
i want to get uid smart card
But I do not know how to set $apdu ?
What is the required amount to receive uid?
example: $apdu = "";
Please help me set the appropriate value for the $ apdu variable instead
thanks.

cardreader : duali dragon
